export enum SecurityEventType {
  FAILED_LOGIN = 'failed_login',
  SUCCESSFUL_LOGIN = 'successful_login',
  PASSWORD_CHANGED = 'password_changed',
  PASSWORD_RESET_REQUESTED = 'password_reset_requested',
  PASSWORD_RESET_COMPLETED = 'password_reset_completed',
  ACCOUNT_LOCKED = 'account_locked',
  ACCOUNT_UNLOCKED = 'account_unlocked',
  ROLE_CHANGED = 'role_changed',
  PERMISSION_CHANGED = 'permission_changed',
  ADMIN_ACCESS = 'admin_access',
  RATE_LIMIT_VIOLATION = 'rate_limit_violation',
  SUSPICIOUS_ACTIVITY = 'suspicious_activity',
  TOKEN_REFRESH = 'token_refresh',
  TOKEN_REVOKED = 'token_revoked',
  EMAIL_CHANGED = 'email_changed',
  PROFILE_UPDATED = 'profile_updated',
}
